import mainTypes from '../mainTypes';

export default {
  ADD_TO_CART: mainTypes.CART_ITEMS + 'ADD_TO_CART',
  REMOVE_TO_CART: mainTypes.CART_ITEMS + 'REMOVE_TO_CART',
  INCREASE_QTY: mainTypes.CART_ITEMS + 'INCREASE_QTY',
  DECREASE_QTY: mainTypes.CART_ITEMS + 'DECREASE_QTY',
  GET_MAIN_CAT: mainTypes.CART_ITEMS + 'GET_MAIN_CAT',
  MANAGE_QTY: mainTypes.CART_ITEMS + 'MANAGE_QTY',
  USER_ID: mainTypes.CART_ITEMS + 'USER_ID',
  LOGIN_TOKEN: mainTypes.CART_ITEMS + 'LOGIN_TOKEN',
  MAIN_CAT_ID: mainTypes.CART_ITEMS + 'MAIN_CAT_ID',
  MAIN_CAT_SLOT: mainTypes.CART_ITEMS + 'MAIN_CAT_SLOT',
  MAIN_CAT_F_TIME_SLOT: mainTypes.CART_ITEMS + 'MAIN_CAT_F_TIME_SLOT',
  MAIN_CAT_NAME: mainTypes.CART_ITEMS + 'MAIN_CAT_NAME',
  OFFER: mainTypes.CART_ITEMS + 'OFFER',
  REMOVE_OFFER: mainTypes.CART_ITEMS + 'REMOVE_OFFER',
  REMOVE_FULL_CART: mainTypes.CART_ITEMS + 'REMOVE_FULL_CART',
  IS_ORDER_TYPE: mainTypes.CART_ITEMS + 'IS_ORDER_TYPE',
  ADD_ALL_CART_DETAILS: mainTypes.CART_ITEMS + 'ADD_ALL_CART_DETAILS',
  TOTAL_QUT: mainTypes.CART_ITEMS + 'TOTAL_QUT',
};
