const productInfoData = {
  category: 'cat1',
  description: {
    briefDescription: 'string',
    formOfProduct: 'Solid',
    fragile: 'Yes',
    highLights: 'string',
    keyWords: 'string',
    otherInformation: 'string',
    packagingHeight: '1.99',
    packagingLength: '1.99',
    packagingWidth: '1.99',
    perisableExpirable: 'Yes',
    relatedDeities: 'string',
    relatedFaith: 'string',
    relatedFestival: 'string',
    replacementAvailable: 'Yes',
    returnAvailable: 'No',
    shelfLife: 'string',
    unitOfPackaging: 'cm',
  },
  images: {
    documentId1: 'DDMS0018',
    documentId2: null,
    documentId3: null,
    documentId4: null,
  },
  info: {
    brandName: 'string',
    cirtificates: 'DDMS0018',
    color: 'string',
    countryOfOrigin: 'string',
    includedItem: 'string',
    lenghtOfProduct: '1.99',
    heightOfProduct: '1.99',
    materialType: 'string',
    onHandQuantity: '12',
    productId: '0',
    productIdType: 'GSTIN',
    productName: 'productName',
    productTitle: 'productTitle',
    productType: 'Simple',
    restockLevel: '40',
    shape: 'Circle',
    stockStatus: 'Available',
    taxClass: 'Taxable',
    unitOfMeasurementDimension: 'cm',
    unitOfMeasurementWeight: 'gm',
    weightOfProduct: '1.99',
    widthOfProduct: '1.99',
  },

  pricing: {
    hsncode: '1234',
    mrp: '1.99',
    onHandUnitCost: '1.99',
    partnerSKUId: 'string',
    yourSellingPrice: '1.99',
  },

  subCategory: 'sub11',
  variation: {
    color: 'string',
    height: '1.99',
    length: '1.99',
    materialType: 'string',
    shape: 'string',
    size: 'string',
    unitQuantity: '1.55',
    width: '1.99',
  },
};

export default productInfoData;
